[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[features]
default = ["extra"]
extra = ["dep:scraper", "dep:serde_json", "dep:percent-encoding", "dep:flate2", "dep:reqwest"]

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }

toml = "*"
url = "2"

log = "*"
annotate-snippets = "0.12"

scraper = { version = "0.27", optional = true }
serde_json = { version = "1", optional = true }
percent-encoding = { version = "2", optional = true }
flate2 = { version = "1", features = ["zlib-rs"], default-features = false, optional = true }
reqwest = { version = "0.13", default-features = false, optional = true, features = [
    "blocking",
    "rustls",
    "gzip",
    "zstd",
] }

[dev-dependencies]

[profile.release]
opt-level = "z"
strip = true
lto = true
codegen-units = 1
panic = "abort"
