[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }

toml = "*"
url = "2"

log = "*"
annotate-snippets = "0.12"

scraper = "0.27"
serde_json = "1"
percent-encoding = "2"
flate2 = { version = "1", features = ["zlib-rs"], default-features = false }
reqwest = { version = "0.13", default-features = false, features = [
    "blocking",
    "rustls",
    "gzip",
    "zstd",
] }

[dev-dependencies]

[profile.release]
opt-level = "z"
strip = true
lto = true
codegen-units = 1
panic = "abort"
