name: CI

on:
  push:
    paths:
      - "data/**"
  pull_request:
    paths:
      - "data/**"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install Rust and Cargo
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run CLI
        working-directory: tools
        run: cargo run -- ../